/**
 * P4-9: Gemini-compatible JSON Schema constant for story generation responses.
 *
 * This schema mirrors the fields validated by `validateStory()` in gemini.ts and
 * the `GeneratedStory` / `GeneratedStoryPage` / `GeneratedStoryNarrativeDevice`
 * TypeScript types in types.ts.
 *
 * PURPOSE:
 *   - Define the JSON Schema shape that will be passed to Gemini's
 *     `generationConfig.responseSchema` in P4-11.
 *   - Serve as a first line of defense against `field_type_mismatch` and
 *     `schema_structural` failures before the response reaches `validateStory()`.
 *   - `validateStory()` remains the runtime source of truth (defense-in-depth).
 *
 * NOT WIRED TO RUNTIME GENERATION YET.
 *   - This file is not imported by gemini.ts or generate-book.ts.
 *   - Wiring happens in P4-11 behind `ENABLE_RESPONSE_SCHEMA` feature flag.
 *
 * DEFERRED FIELDS (intentionally not included in this schema):
 *   - `storyModel`, `storyModelFallbackUsed`, `storyGenerationAttempts`:
 *     These are client-side metadata added after generation, not part of
 *     the LLM output.
 *   - `cast[].referenceImageUrl`, `cast[].approvedImageUrl`,
 *     `cast[].generatedReferenceImageUrl`, `cast[].referenceImageGeneratedAt`,
 *     `cast[].referenceImagePrompt`, `cast[].referenceImageStatus`:
 *     These are app-managed fields, not generated by the LLM.
 *   - `minItems`/`maxItems` for pages array: Gemini JSON Schema subset may not
 *     enforce these. Page count validation remains in `validateStory()` and
 *     the quality gate.
 *
 * PRIVACY: This schema contains no user PII, no prompt text, and no story content.
 */

import { PAGE_VISUAL_ROLES } from "./types";

// ---------------------------------------------------------------------------
// Schema version — bump when the schema shape changes.
// ---------------------------------------------------------------------------

/** Semantic version for the story response schema. */
export const STORY_RESPONSE_SCHEMA_VERSION = "1.0.0";

// ---------------------------------------------------------------------------
// Enum values (derived from TypeScript types for single source of truth)
// ---------------------------------------------------------------------------

const PAGE_VISUAL_ROLE_ENUM = [...PAGE_VISUAL_ROLES];

const STORY_CHARACTER_ROLE_ENUM = [
  "protagonist",
  "buddy",
  "parent",
  "sibling",
  "animal",
  "magical_friend",
  "object_character",
  "background_recurring",
] as const;

const STORY_CHARACTER_KIND_ENUM = [
  "human_child",
  "human_adult",
  "animal",
  "magical_creature",
  "object_character",
  "background",
] as const;

// ---------------------------------------------------------------------------
// Sub-schemas
// ---------------------------------------------------------------------------

const NARRATIVE_DEVICE_SCHEMA = {
  type: "object" as const,
  properties: {
    repeatedPhrase: { type: "string" as const, nullable: true },
    visualMotif: { type: "string" as const, nullable: true },
    setup: { type: "string" as const, nullable: true },
    payoff: { type: "string" as const, nullable: true },
    hiddenDetails: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
  },
  nullable: true,
};

const PAGE_SCHEMA = {
  type: "object" as const,
  properties: {
    text: { type: "string" as const, description: "Story text for this page (read-aloud)" },
    imagePrompt: { type: "string" as const, description: "Image generation prompt for this page" },
    compositionHint: { type: "string" as const, nullable: true },
    visualMotifUsage: { type: "string" as const, nullable: true },
    hiddenDetail: { type: "string" as const, nullable: true },
    pageVisualRole: {
      type: "string" as const,
      enum: PAGE_VISUAL_ROLE_ENUM,
      nullable: true,
    },
    appearingCharacterIds: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
    focusCharacterId: { type: "string" as const, nullable: true },
    sourcePhotoIndex: { type: "number" as const, nullable: true },
  },
  required: ["text", "imagePrompt"] as const,
};

const CAST_CHARACTER_SCHEMA = {
  type: "object" as const,
  properties: {
    characterId: { type: "string" as const },
    displayName: { type: "string" as const },
    role: {
      type: "string" as const,
      enum: [...STORY_CHARACTER_ROLE_ENUM],
    },
    visualBible: { type: "string" as const },
    characterKind: {
      type: "string" as const,
      enum: [...STORY_CHARACTER_KIND_ENUM],
      nullable: true,
    },
    nonHuman: { type: "boolean" as const, nullable: true },
    noHumanFace: { type: "boolean" as const, nullable: true },
    noHumanBody: { type: "boolean" as const, nullable: true },
    scaleHint: { type: "string" as const, nullable: true },
    silhouette: { type: "string" as const, nullable: true },
    colorPalette: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
    signatureItems: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
    doNotChange: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
    negativeCharacterRules: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
    canChangeByScene: {
      type: "array" as const,
      items: { type: "string" as const },
      nullable: true,
    },
  },
  required: ["characterId", "displayName", "role", "visualBible"] as const,
};

// ---------------------------------------------------------------------------
// Root schema
// ---------------------------------------------------------------------------

/**
 * Gemini-compatible JSON Schema for the story generation response.
 *
 * Intended for use in `generationConfig.responseSchema` (P4-11).
 * NOT wired to runtime generation in P4-9.
 */
export const STORY_RESPONSE_SCHEMA = {
  type: "object" as const,
  properties: {
    title: {
      type: "string" as const,
      description: "Book title in Japanese",
    },
    characterBible: {
      type: "string" as const,
      description: "Detailed visual description of the child protagonist for consistent illustration",
    },
    styleBible: {
      type: "string" as const,
      description: "Illustration style description for consistent page images",
    },
    storyGoal: {
      type: "string" as const,
      description: "Central narrative goal of the story",
      nullable: true,
    },
    mainQuestObject: {
      type: "string" as const,
      description: "Primary quest object as a single string, not an array",
      nullable: true,
    },
    forbiddenQuestObjects: {
      type: "array" as const,
      items: { type: "string" as const },
      description: "Objects that must not become the main quest",
      nullable: true,
    },
    titleSpreadText: {
      type: "string" as const,
      description: "Text for the title spread page",
      nullable: true,
    },
    openingNarration: {
      type: "string" as const,
      description: "Opening narration text",
      nullable: true,
    },
    coverImagePrompt: {
      type: "string" as const,
      description: "Image prompt for the book cover",
      nullable: true,
    },
    narrativeDevice: NARRATIVE_DEVICE_SCHEMA,
    cast: {
      type: "array" as const,
      items: CAST_CHARACTER_SCHEMA,
      nullable: true,
    },
    pages: {
      type: "array" as const,
      items: PAGE_SCHEMA,
      description: "Story pages with text and image prompts",
    },
  },
  required: ["title", "characterBible", "styleBible", "pages"] as const,
};

// ---------------------------------------------------------------------------
// Convenience exports for tests
// ---------------------------------------------------------------------------

/** Root-level required fields (must match validateStory() requirements). */
export const STORY_RESPONSE_SCHEMA_REQUIRED_FIELDS = STORY_RESPONSE_SCHEMA.required;

/** Page-level required fields (must match validateStory() per-page requirements). */
export const STORY_PAGE_REQUIRED_FIELDS = PAGE_SCHEMA.required;

// ---------------------------------------------------------------------------
// Minimal schema variant (P4-12f spike)
// ---------------------------------------------------------------------------
//
// P4-12e showed that the full STORY_RESPONSE_SCHEMA inflates Gemini structured
// output to 300–346K chars, exceeding the model's output token limit.
//
// This minimal schema keeps only the envelope fields needed to produce a
// parseable story JSON. All optional/semantic fields are intentionally excluded
// to reduce structured output pressure. validateStory() remains the runtime
// validator and will accept/normalize any extra fields Gemini emits via prompt
// instructions.
//
// NOT WIRED TO RUNTIME. This is a spike artifact for size comparison and
// potential future P4-12g live smoke.

/** Semantic version for the minimal schema variant. */
export const STORY_RESPONSE_SCHEMA_MINIMAL_VERSION = "0.1.0";

const MINIMAL_PAGE_SCHEMA = {
  type: "object" as const,
  properties: {
    text: { type: "string" as const, description: "Story text for this page (read-aloud)" },
    imagePrompt: { type: "string" as const, description: "Image generation prompt for this page" },
  },
  required: ["text", "imagePrompt"] as const,
};

/**
 * Minimal Gemini-compatible JSON Schema for the story generation response.
 *
 * Keeps only the must-have envelope fields:
 *   root: title, characterBible, styleBible, pages
 *   page: text, imagePrompt
 *
 * All optional fields (cast, narrativeDevice, storyGoal, mainQuestObject,
 * forbiddenQuestObjects, titleSpreadText, openingNarration, coverImagePrompt,
 * pageVisualRole, compositionHint, visualMotifUsage, hiddenDetail,
 * appearingCharacterIds, focusCharacterId) are intentionally excluded.
 *
 * NOT WIRED TO RUNTIME GENERATION. Spike only (P4-12f).
 */
export const STORY_RESPONSE_SCHEMA_MINIMAL = {
  type: "object" as const,
  properties: {
    title: {
      type: "string" as const,
      description: "Book title in Japanese",
    },
    characterBible: {
      type: "string" as const,
      description: "Detailed visual description of the child protagonist for consistent illustration",
    },
    styleBible: {
      type: "string" as const,
      description: "Illustration style description for consistent page images",
    },
    pages: {
      type: "array" as const,
      items: MINIMAL_PAGE_SCHEMA,
      description: "Story pages with text and image prompts",
    },
  },
  required: ["title", "characterBible", "styleBible", "pages"] as const,
};

/** Root-level required fields for minimal schema. */
export const STORY_RESPONSE_SCHEMA_MINIMAL_REQUIRED_FIELDS =
  STORY_RESPONSE_SCHEMA_MINIMAL.required;

/** Page-level required fields for minimal schema. */
export const STORY_RESPONSE_SCHEMA_MINIMAL_PAGE_REQUIRED_FIELDS =
  MINIMAL_PAGE_SCHEMA.required;
