import { initializeApp, getApps } from "firebase-admin/app";

if (getApps().length === 0) initializeApp();

export { generateBook } from "./generate-book";
export { deleteBook } from "./delete-book";
export { deleteChildProfile } from "./delete-child-profile";
export { deleteUserAccount } from "./delete-user-account";
export { cleanupExpired } from "./cleanup-expired";
export { resetMonthlyQuota } from "./reset-monthly-quota";
export { seedTemplates } from "./seed-templates";
export { testImageModels } from "./test-image-models";
export { regenerateStylePreviews } from "./regenerate-style-previews";
export { bootstrapAdmin } from "./bootstrap-admin";
export { regeneratePageImage, checkBookCompletion } from "./regenerate-page-image";
export { regenerateCoverImage } from "./regenerate-cover-image";
export { saveDailySloSnapshot } from "./save-daily-slo-snapshot";
export { saveWeeklySloSnapshot } from "./save-weekly-slo-snapshot";
export { saveWeeklyQualitySnapshot } from "./save-weekly-quality-snapshot";
export { saveDailyMetricsSnapshot, backfillDailyMetrics } from "./save-daily-metrics-snapshot";
export { createCoupon, redeemCoupon } from "./coupons";
export { cleanupStaleGeneration } from "./cleanup-stale-generation";
export { createCheckoutSession, createSinglePurchaseCheckout, stripeWebhook, createOrgCheckoutSession } from "./stripe-checkout";
export { onAvatarJobCreated } from "./generate-avatar-job";
export { generateTemplate } from "./generate-template";
export { onCompanionImageJobCreated } from "./generate-companion-image";
export { generateStoryPitch } from "./generate-story-pitch";
export { analyzeChildPhoto } from "./analyze-child-photo";
export { onBookCompletion_triggerLLMAutoReview } from "./auto-review";
export { submitAppFeedback } from "./submit-app-feedback";
export { updateBookTitle } from "./update-book-title";
export { updateBookPageText } from "./update-page-text";
export { generateBookPdf } from "./generate-book-pdf";
export { createOrganization, joinOrganizationByCode, rotateInviteCode, leaveOrganization, removeOrgMember } from "./organizations";
export { bulkGenerateClassBooks } from "./bulk-generate";
